kind: Namespace
apiVersion: v1
metadata:
  name: home
  labels:
    name: home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: home
spec:
  revisionHistoryLimit: 0 
  selector:
    matchLabels:
      run: home
  replicas: 1
  template:
    metadata:
      labels:
        run: home
    spec:
      containers:
      - name: home
        image: ghcr.io/loeksangers/personal-website:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 60
      volumes:
      - name: home-data
        nfs:
          server: 192.168.2.110
          path: /home
---
apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: home
  labels:
    run: home
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ingress
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: loeksangers.nl
    http:
      paths:
      - backend:
          service:
            name: home
            port:
              number: 80
        path: /
        pathType: Prefix
# This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - loeksangers.nl
        - www.loeksangers.nl
      secretName: loeksangers.nl-tls
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.109
